### ISSUE TITLE
Bug: Not async export on use server file

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/ForVoyez#219]
POST / 500 in 106ms
 ⨯ Error: A "use server" file can only export async functions, found object.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value
    at eval (./src/services/database.service.js:264:91)
    at (action-browser)/./src/services/database.service.js (/home/andycinquin/ClonedRepo/ForVoyez/.next/server/app/page.js:704:1)
    at Function.__webpack_require__ (/home/andycinquin/ClonedRepo/ForVoyez/.next/server/webpack-runtime.js:33:43)
digest: "1999519948"
 POST / 500 in 17ms
 GET /?_rsc=r3yhw 200 in 19ms
 ✓ Compiled in 1217ms (1575 modules)
 ✓ Compiled in 614ms (1575 modules)
 ⨯ ./src/services/database.service.js

![image](https://github.com/For-Hives/ForVoyez/assets/55706543/63d7242b-b43b-4167-85a6-87c3ee50b83e)

**Comment by LightInn** [comment]
ah ? j'ai fait une betise ? :c

**Comment by CinquinAndy** [comment]
yes i think so'
