### ISSUE TITLE
test flawky

### ISSUE THREAD

**Issue by LightInn** [For-Hives/ForVoyez#285]
![image](https://github.com/For-Hives/ForVoyez/assets/28759336/8816f3b4-5a9c-477a-821d-9dbd4b9a84de)

```
·

  1) [general] › tests***e2e***general***app-basic-acc***app-playground.spec.js:10:2 › Playground Functionality › Check playground usage tooltip and redirection 

    Error: Timed out 5000ms waiting for expect(locator).toBeVisible()

    Locator: locator('[data-testid="tooltip-link"]')
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for locator('[data-testid="tooltip-link"]')


      14 | 		const tooltipLocator = page.locator('[data-testid="tooltip-link"]')
      15 | 		log('Checking presence of the tooltip')
    > 16 | 		await expect(tooltipLocator).toBeVisible()
         | 		                             ^
      17 |
      18 | 		*** Verify the text content of the tooltip
      19 | 		const tooltipText = await tooltipLocator.innerText()

        at ***home***runner***work***ForVoyez***ForVoyez***tests***e2e***general***app-basic-acc***app-playground.spec.js:16:32

    attachment #1: video (video***webm) ──────────────────────────────────────────────────────────────
    test-results***app-basic-acc-app-playgrou-200f8-age-tooltip-and-redirection-general***video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toBeVisible()

    Locator: locator('[data-testid="tooltip-link"]')
    Expected: visible
    Received: <element(s) not found>
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for locator('[data-testid="tooltip-link"]')


      14 | 		const tooltipLocator = page.locator('[data-testid="tooltip-link"]')
      15 | 		log('Checking presence of the tooltip')
    > 16 | 		await expect(tooltipLocator).toBeVisible()
         | 		                             ^
      17 |
      18 | 		*** Verify the text content of the tooltip
      19 | 		const tooltipText = await tooltipLocator.innerText()

        at ***home***runner***work***ForVoyez***ForVoyez***tests***e2e***general***app-basic-acc***app-playground.spec.js:16:32

    attachment #1: video (video***webm) ──────────────────────────────────────────────────────────────
    test-results***app-basic-acc-app-playgrou-200f8-age-tooltip-and-redirection-general-retry1***video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #2: trace (application***zip) ─────────────────────────────────────────────────────────
    test-results***app-basic-acc-app-playgrou-200f8-age-tooltip-and-redirection-general-retry1***trace.zip
    Usage:

        pnpm exec playwright show-trace test-results***app-basic-acc-app-playgrou-200f8-age-tooltip-and-redirection-general-retry1***trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 failed
    [general] › tests***e2e***general***app-basic-acc***app-playground.spec.js:10:2 › Playground Functionality › Check playground usage tooltip and redirection 
  19 passed (33.5s)
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.

```

**Comment by LightInn** [comment]
should be fixed with #645
